-- Run once in the Supabase SQL Editor for the project used by this site.
create table if not exists public.redesign_submissions (
  id bigint generated by default as identity primary key,
  work_email text not null check (char_length(work_email) between 3 and 320),
  company_url text not null check (char_length(company_url) between 4 and 2048),
  x_handle text not null check (char_length(x_handle) between 2 and 2048),
  role text not null check (role in ('Founder', 'Marketing', 'Product', 'Design', 'Other')),
  role_other text check (role_other is null or char_length(role_other) between 1 and 120),
  company_stage text not null check (
    company_stage in ('Pre-revenue', '<$500k ARR', '$500k–$2M ARR', '$2M–$10M ARR', '$10M+ ARR')
  ),
  improvement_goal text not null check (char_length(improvement_goal) between 1 and 4000),
  created_at timestamptz not null default now(),
  constraint redesign_submissions_other_role_check check (
    (role = 'Other' and role_other is not null and char_length(btrim(role_other)) > 0)
    or (role <> 'Other' and role_other is null)
  )
);

comment on table public.redesign_submissions is 'Private lead submissions from the free hero redesign page.';

alter table public.redesign_submissions enable row level security;

-- Browsers never access this table directly. Only the server-side secret/service
-- role may insert or read rows through the Data API.
revoke all on table public.redesign_submissions from anon, authenticated;
grant select, insert on table public.redesign_submissions to service_role;
grant usage, select on sequence public.redesign_submissions_id_seq to service_role;

create index if not exists redesign_submissions_created_at_idx
  on public.redesign_submissions (created_at desc);
